### PR TITLE
Replace import and support Angular Material 12

### PR DESCRIPTION
**Pull request by parse**
Fixes https://github.com/HaidarZ/ng-mat-select-infinite-scroll/issues/18

### CODE REVIEW

**Comment by HaidarZ** [comment]
Much appreciated, will review the changes and merge asap.

**Comment by zach-snell** [comment]
@HaidarZ couple of us on my project took a look at the changes yesterday. They look reasonable and the constant is identical to Angular 12 which just no longer exposes it publically.

Can you merge this in? Thanks!

**Review by HaidarZ — CHANGES_REQUESTED** [review]
use `import {SELECT_ITEM_HEIGHT_EM} from '@angular/material/select/select';` instead of declaring a new constant.  
Most probably `SELECT_ITEM_HEIGHT_EM` have been removed from the public api by mestake.

**Comment by zach-snell** [comment]
@HaidarZ Looks like Angular replied on the linked thread that the removal was intentional and completion of API that were marked deprecated and to be removed in 12.

**Comment by jawaddev** [comment]
@HaidarZ any updates on when this will be merged? as @zach-snell said it was the removal was intentional.

**Comment by angelaki** [comment]
Guess you are still hoping for a more satisfactory answer from the Angular Team than just assume **3**?

**Comment by HaidarZ** [comment]
Sorry guys,I was trying to stick to the flow and standards.
There's no official depreciation notice or comment inside the docstring.
Typically they must inform users that in the next release the following must be removed.
Anyways, the wait is over. Thanks for your patience.

**Pull request merged**
